const OBJECT_ACTION = {
    DETAIL_COMIC: 'DETAIL_COMIC', 
    CATEGORY_COMIC: 'CATEGORY_COMIC', 
    ITEM_CHAP_COMIC: 'ITEM_CHAP_COMIC', 
    CATEGORIES: 'CATEGORIES',
    FULL_COMIC: 'FULL_COMIC',
    LAST_CHAP_COMIC: 'LAST_CHAP_COMIC',
    NEW_COMIC: 'NEW_COMIC',
    TABLE_COMIC: 'TABLE_COMIC'
};

export {
    OBJECT_ACTION
}